var Chinese = {
  button: "English",
  mypublish:"我发布的",
  mynews:"消息列表",
  feedback:"意见反馈",
  scan:"绑定网关",
  deleteGateway:"解绑网关",
  refreshGateway:"设备入网",
  share:'分享网关',
  unshare: '取消分享',
  myfeedback:"如果您有任何建议或想法，请联系我：）",
  search:"请输入搜索内容",
  content:"您要发布的内容...",
  comment: "评论",
  submit:"发布",
  place:"所在位置",
  alldevice:"所有设备",
  bulb:"灯泡",
  socket:"插座",
  curtain:"窗帘",
  sensor:"传感器",
  swi:"开关",
  monitor:"监控",
  lock:"门锁",
  othertypes:"其他类型",
  scenetypes:"场景开关",
  temperature:"温度",
  humidity:"湿度",
  infrared:"红外宝",
  name:"名称",
  success:"应用成功",
  failure:"应用失败",
  welcome:"启动未来",
  register: '注册',
  email:'请输入邮箱',
  phone:'请输入电话',
  userreg:'用户注册',
  failed:'登录失败',
  failedmess:"未查询到相关信息，请您先注册",
  del:'删除',
  delmes: '确定要删除该条信息吗？',
  loading:'登录中',
  wrong:'获取失败'

}

module.exports = {
  Content: Chinese
}