var English = {
  button: "中文",
  mypublish: "Album",
  mynews: "Friends' Comments",
  feedback: "Feedback",
  scan:"scan",
  myfeedback: "If you have any suggessions,please contact me",
  search: "Search...",
  content: "What do you want to say...",
  comment: "Comment",
  submit: "Post",
  place: "Location",
  alldevice: "All equipment",
  bulb: "Bulb",
  socket: "Socket",
  curtain: "Curtain",
  sensor: "Sensor",
  swi: "Switch",
  othertypes: "Other types",
  temperature: "Temperature",
  humidity: "humidity",
  name: "name",
  success: "success",
  failure: "failure",
  introduce: "Gantch Smart Technology Shares Ltd. is a IOT smart products R & D, design, production, sales and service as one of the diversified high-tech enterprises. Products relates to IOT Smart home control system and IOT smart control system of agriculture, urban network security alarm system, IP/GPRS/PSTN multi network interconnection control system, Perimeter alarm system, Internet video monitoring system, urban anti-terrorism system series of high-tech products.Gantch smart technology development oriented, focus on technology innovation, the technology research and development centers are located in Beijing and Shenzhen of China, partners with professional and technical personnel and the strong support of international cooperation, and the strong backing of Chinese Academy of Sciences.Gantch wisdom Home Furnishing intelligent home appliances, intelligent curtain, intelligent lighting, background music, intelligent security, video surveillance, access control, environmental monitoring, intelligent management of health care equipment, let you no matter where, all can manage your home, make your life more healthy, comfortable, convenient and safe.As Gantch in the industry took the lead through the ISO9001 international quality management system certification.Products by the national Ministry of public security testing center inspection and comprehensive through the CCC, CE, FCC, RoHS and other international certification.Products have been exported to Europe, Asia, America more than 50 countries and regions, with China Petroleum, China petrochemical and other international well - known enterprises to establish a long-term cooperative relations, Gantch as CSGIA member units and SSPIA member units to prevent, consecutive years won the 'Chinese consumers are satisfied with the famous brand', 'Safe city construction recommended brand'、'Product quality user enterprise' and other honorary titles.",
  welcome: "It's time for smart living",
  register: 'Create an account',
  email: 'Email...',
  phone: 'Phone...',
  userreg: 'Sing up',
  failed: 'Login failure',
  failedmess: "We did't find your informaton,please sign up firstly.",
  del: 'Delete',
  delmes: 'Are you sure you want to do this?',
  loading: 'Loading',
  wrong: "Can't get your location"
}

module.exports = {
  Content: English
}