var English = {
  button: "中文",
  mypublish: "Album",
  mynews: "Friends' Comments",
  feedback: "Feedback",
  scan:"Add Gateway",
  deleteGateway:"Delete Gateway",
  refreshGateway:"Equipment access network",
  share:'Sharing gateway',
  unshare:'Unshare Gateway',
  myfeedback: "If you have any suggessions,please contact me",
  search: "Search...",
  content: "What do you want to say...",
  comment: "Comment",
  submit: "Post",
  place: "Location",
  alldevice: "All equipment",
  bulb: "Bulb",
  socket: "Socket",
  curtain: "Curtain",
  sensor: "Sensor",
  swi: "Switch",
  monitor: "Monitor",
  lock: "Gate lock",
  othertypes: "Other types",
  scenetypes: "Scene types",
  temperature: "Temperature",
  humidity: "humidity",
  infrared: "infrared",
  name: "name",
  success: "success",
  failure: "failure",
  welcome: "It's time for smart living",
  register: 'Create an account',
  email: 'Email...',
  phone: 'Phone...',
  userreg: 'Sing up',
  failed: 'Login failure',
  failedmess: "We did't find your informaton,please sign up firstly.",
  del: 'Delete',
  delmes: 'Are you sure you want to do this?',
  loading: 'Loading',
  wrong: "Can't get your location"
}

module.exports = {
  Content: English
}